# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqnNJSfbrbinKaIoyZnW9OnqXMFGNqPl
"""

#Create an interactive choropleth map using Plotly to visualize global installs by categories .
#Apply filters to show data for only the top 5 app categories and highlight categories where the number of installs exceeds 1 million and App category should not start with character “A” , “C” , “G” and “S” .
#this graph should work only between 6PM IST to 8 PM IST apart from that time we should not show this graph in dashboard itself

import pandas as pd
import plotly.express as px
from datetime import datetime
import pytz

data = pd.read_csv('C:/Users/sowmi/OneDrive/Documents/AI/Nullclass/Play Store Data.csv', encoding='utf-8', on_bad_lines='skip')

data = data[data['Price'] != "Everyone"]

data['Price'] = data['Price'].apply(lambda x: str(x).replace('$', '') if isinstance(x, str) else x).astype(float)


data['Installs'] = data['Installs'].str.replace(r'[^\d]', '', regex=True).astype(int)

data['Revenue'] = data['Price'] * data['Installs']
data['Revenue'] = data['Revenue'].apply(lambda x: int(round(x)))

excluded_categories = ['A', 'C', 'G', 'S']
data = data[~data['Category'].str.startswith(tuple(excluded_categories))]

data = data[~data['Size'].isin(['Varies with device'])]
data = data[~data['Size'].str.contains('k')]
data['Size'] = data['Size'].str.replace('M', '').astype(float)

data = data[data['Size'] > 1]

top_5_categories = data.nlargest(5, 'Installs')

filtered_data = data[data['Category'].isin(top_5_categories['Category'])]

final_grouped_data = filtered_data.groupby(['Category', 'Country'])['Installs'].sum().reset_index()

def within_time_window():
    ist = pytz.timezone('Asia/Kolkata')
    current_time = datetime.now(ist)
    return 18 <= current_time.hour < 20

if within_time_window():

    fig = px.choropleth(
        final_grouped_data,
        locations='Country',
        locationmode='country names',
        color='Installs',
        hover_name='Category',
        title='Global Installs by Top 5 App Categories',
        color_continuous_scale=px.colors.sequential.Plasma
    )


    fig.write_html('dashboard3.html')
    print("Graph generated and saved as 'dashboard3.html'.")
else:
    print("This graph is only available between 6 PM and 8 PM IST.")