# -*- coding: utf-8 -*-
"""Task5ViolinChart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1153qXpvSy5CzW5BJvPsUccbcuRdAGadZ
"""

#Create a violin plot to visualize the distribution of ratings for each app category, but only include categories with more than 50 apps and app name should contain letter “C” and exclude apps with fewer than 10 reviews and rating should be less 4.0.
#this graph should work only between 4 PM IST to 6 PM IST apart from that time we should not show this graph in dashboard itself.



import pandas as pd
import plotly.express as px
from datetime import datetime
import pytz

data = pd.read_csv('C:/Users/sowmi/OneDrive/Documents/AI/Nullclass/Play Store Data.csv', encoding='utf-8', on_bad_lines='skip')

data['Reviews'] = pd.to_numeric(data['Reviews'], errors='coerce')
data['Rating'] = pd.to_numeric(data['Rating'], errors='coerce')

filtered_data = data.loc[
    (data['App'].str.contains('C', case=False, na=False)) &
    (data['Reviews'] >= 10) &
    (data['Rating'] < 4.0)
].copy()

category_counts = filtered_data['Category'].value_counts()
valid_categories = category_counts[category_counts > 50].index.tolist()


filtered_data = filtered_data[filtered_data['Category'].isin(valid_categories)]

def within_time_window():
    ist = pytz.timezone('Asia/Kolkata')
    current_time = datetime.now(ist)
    return 16 <= current_time.hour < 18


if within_time_window():
    fig = px.violin(
        filtered_data,
        x='Category',
        y='Rating',
        box=True,
        points='all',
        title="Distribution of Ratings by App Category",
        labels={'Category': 'App Category', 'Rating': 'App Rating'},
        color='Category',
        template="plotly_dark"
    )

    fig.write_html('dashboard5.html')
    print("Graph generated and saved as 'dashboard5.html'.")
else:
    print("This graph is only available between 4 PM and 6 PM IST.")